class DiseaseInfo {
  final String name;
  final String description;
  final List<String> symptoms;
  final List<String> causes;
  final List<String> treatments;
  final List<String> prevention;
  final String severity;
  final String iconEmoji;

  DiseaseInfo({
    required this.name,
    required this.description,
    required this.symptoms,
    required this.causes,
    required this.treatments,
    required this.prevention,
    required this.severity,
    required this.iconEmoji,
  });

  static final Map<String, DiseaseInfo> diseaseDatabase = {
    'Bacterialblight': DiseaseInfo(
      name: 'Bacterial Blight',
      description:
          'A serious bacterial disease caused by Xanthomonas oryzae pv. oryzae. It affects rice at all growth stages and can cause severe yield losses of 20-80% if not controlled early.',
      symptoms: [
        'Water-soaked lesions on leaf tips and margins',
        'Yellow to white lesions with wavy edges',
        'Milky bacterial ooze from cut lesions (morning)',
        'Leaves turn grayish-white and die (kresek symptom)',
        'Systemic infection causes wilting of whole plant',
        'Young plants may die within 2-3 weeks',
      ],
      causes: [
        'Xanthomonas oryzae pv. oryzae bacteria',
        'High humidity (>70%) and temperature (25-34°C)',
        'Infected seeds or contaminated tools',
        'Wounds from insects or wind damage',
        'Deep water in fields',
        'Excessive nitrogen fertilization',
        'Use of susceptible varieties',
      ],
      treatments: [
        'Chemical Control:',
        '  • Copper oxychloride 50% WP @ 600g/acre',
        '  • Streptocycline @ 200g/acre (15g in 100L water)',
        '  • Plantomycin @ 200g/acre',
        '  • Bronopol 20% SL @ 200ml/acre',
        '',
        'Application Guidelines:',
        '  • Spray at early disease appearance',
        '  • Repeat after 10-12 days if needed',
        '  • Use 200-250 liters of water per acre',
        '  • Apply during early morning',
        '',
        'Cultural Practices:',
        '  • Remove and burn infected plants immediately',
        '  • Improve field drainage (avoid deep water)',
        '  • Reduce nitrogen fertilizer temporarily',
        '  • Apply potassium to strengthen plants',
        '  • Disinfect tools with bleach solution',
        '',
        'Emergency Measures:',
        '  • Drain water from field for 4-5 days',
        '  • Cut and burn severely infected leaves',
        '  • Apply copper-based bactericide immediately',
      ],
      prevention: [
        'Use resistant varieties (IR64, Swarna, Pusa Basmati 1)',
        'Treat seeds with antibiotics before sowing',
        'Use certified disease-free seeds',
        'Avoid excessive nitrogen (use balanced NPK)',
        'Maintain shallow water depth (5 cm max)',
        'Ensure proper plant spacing (20×15 cm)',
        'Remove crop residues and weeds after harvest',
        'Avoid injury to plants during field operations',
        'Practice crop rotation (avoid continuous rice)',
        'Apply silicon and potassium fertilizers',
        'Monitor fields weekly during rainy season',
      ],
      severity: 'High - CRITICAL',
      iconEmoji: '🦠',
    ),
    'Brownspot': DiseaseInfo(
      name: 'Brown Spot Disease',
      description:
          'A fungal disease caused by Bipolaris oryzae. Often called "seedling blight" when it affects young plants. Can reduce yield by 10-50% and grain quality significantly.',
      symptoms: [
        'Circular to oval brown spots on leaves',
        'Gray to brown center with reddish-brown margins',
        'Spots range from pin-point to 1 cm diameter',
        'Multiple spots may coalesce forming large patches',
        'Infected grains show dark brown to black discoloration',
        'Seedlings may die if severely infected',
      ],
      causes: [
        'Bipolaris oryzae fungus',
        'Nutrient deficiency (especially nitrogen and silicon)',
        'Poor soil fertility and drainage',
        'High humidity (>80%) with leaf wetness',
        'Temperature between 25-30°C',
        'Infected seeds or crop residues',
        'Drought stress or water scarcity',
      ],
      treatments: [
        'Chemical Control:',
        '  • Mancozeb 75% WP @ 600-800g/acre',
        '  • Carbendazim 50% WP @ 200g/acre',
        '  • Propiconazole 25% EC @ 200ml/acre',
        '  • Tricyclazole 75% WP @ 120g/acre',
        '  • Hexaconazole 5% SC @ 400ml/acre',
        '',
        'Application Schedule:',
        '  • First spray: At tillering stage',
        '  • Second spray: 15 days after first spray',
        '  • Third spray: At panicle initiation if severe',
        '  • Use 200 liters of water per acre',
        '',
        'Nutrient Management (CRITICAL):',
        '  • Apply balanced NPK fertilizer (120:60:40)',
        '  • Add zinc sulfate @ 25kg/acre',
        '  • Apply potassium sulfate @ 25kg/acre',
        '  • Use silicon fertilizers (calcium silicate @ 30kg/acre)',
        '',
        'Cultural Practices:',
        '  • Improve field drainage',
        '  • Maintain proper water levels',
        '  • Remove severely infected leaves',
        '  • Increase organic matter in soil',
      ],
      prevention: [
        'Use healthy, disease-free certified seeds',
        'Treat seeds with Carbendazim @ 2g/kg seed',
        'Maintain proper soil nutrient levels',
        'Apply balanced fertilizers (avoid deficiency)',
        'Ensure good field drainage',
        'Apply potassium and zinc at planting',
        'Use silicon fertilizers (strengthen cell walls)',
        'Avoid water stress (maintain adequate irrigation)',
        'Practice crop rotation',
        'Remove and burn crop residues',
        'Plant at recommended spacing (20×15 cm)',
        'Monitor nutrient deficiency symptoms',
      ],
      severity: 'Medium to High',
      iconEmoji: '🟤',
    ),
    'Leafsmut': DiseaseInfo(
      name: 'Leaf Smut Disease',
      description:
          'A fungal disease caused by Entyloma oryzae. Produces characteristic black spots on leaves. Generally less severe than other diseases but can reduce photosynthesis and weaken plants.',
      symptoms: [
        'Small black angular or elongated spots on leaves',
        'Spots are 0.5-2 mm in size, slightly raised',
        'Black sori (fungal spore masses) on both leaf surfaces',
        'Spots may have yellow halo around them',
        'Heavy infection causes leaves to appear dirty/sooty',
        'Severely infected leaves may turn yellow and dry',
      ],
      causes: [
        'Entyloma oryzae fungus',
        'High humidity (>85%) and cool temperatures (20-25°C)',
        'Prolonged leaf wetness (dew, rain)',
        'Dense plant canopy with poor air circulation',
        'Excessive nitrogen fertilization',
        'Shaded conditions',
        'Infected crop residues',
      ],
      treatments: [
        'Chemical Control:',
        '  • Propiconazole 25% EC @ 200ml/acre',
        '  • Copper oxychloride 50% WP @ 600g/acre',
        '  • Mancozeb 75% WP @ 600g/acre',
        '  • Chlorothalonil 75% WP @ 400g/acre',
        '',
        'Application Guidelines:',
        '  • Spray at first appearance of symptoms',
        '  • Repeat after 12-15 days if needed',
        '  • Ensure complete leaf coverage',
        '  • Spray early morning or evening',
        '',
        'Cultural Practices:',
        '  • Remove heavily infected leaves',
        '  • Improve air circulation in field',
        '  • Reduce plant density if too crowded',
        '  • Avoid overhead irrigation',
        '  • Ensure proper drainage',
        '',
        'Nutrient Management:',
        '  • Reduce nitrogen if over-applied',
        '  • Apply balanced NPK fertilization',
        '  • Increase potassium to strengthen plants',
      ],
      prevention: [
        'Plant resistant or tolerant varieties',
        'Maintain proper plant spacing (20×15 cm)',
        'Avoid overcrowding of plants',
        'Ensure good field drainage and air circulation',
        'Avoid excessive nitrogen fertilization',
        'Use balanced NPK ratio (120:60:40)',
        'Remove and burn crop residues after harvest',
        'Practice crop rotation',
        'Avoid planting in shaded areas',
        'Monitor during humid/rainy periods',
        'Apply potassium fertilizers for plant vigor',
        'Keep fields weed-free for better air flow',
      ],
      severity: 'Low to Medium',
      iconEmoji: '⚫',
    ),
  };

  static DiseaseInfo? getInfo(String diseaseName) {
    return diseaseDatabase[diseaseName];
  }

  static List<String> getAllDiseaseNames() {
    return diseaseDatabase.keys.toList();
  }
}
